package git.doomshade.aoc._92;

import git.doomshade.aoc.shared.Util;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * <h2>--- Day 9: Rope Bridge ---</h2><p>This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.</p>
 * <p>It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.</p>
 * <p>You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where <em>not</em>
 * to step.</p>
 * <p>Consider a rope with a knot at each end; these knots mark the <em>head</em> and the <em>tail</em> of the rope. If the head moves far enough away from the tail, the
 * tail is pulled toward the head.</p>
 * <p>Due to nebulous reasoning involving <a href="https://en.wikipedia.org/wiki/Planck_units#Planck_length" target="_blank">Planck lengths</a>
 * , you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical <em>series of motions</em> (your puzzle input) for the
 * head, you can determine how the tail will move.</p>
 * <p><span title="I'm an engineer, not a physicist!">Due to the aforementioned Planck lengths</span>, the rope must be quite short; in fact, the head (<code>H</code>) and
 * tail (<code>T</code>) must <em>always be touching</em> (diagonally adjacent and even overlapping both count as touching):</p>
 * <pre><code>
 * ....
 * .TH.
 * ....
 *
 * ....
 * .H..
 * ..T.
 * ....
 *
 * ...
 * .H. (H covers T)
 * ...
 * </code></pre>
 * <p>If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:</p>
 * <pre><code>
 * .....    .....    .....
 * .TH.. -&gt; .T.H. -&gt; ..TH.
 * .....    .....    .....
 *
 * ...    ...    ...
 * .T.    .T.    ...
 * .H. -&gt; ... -&gt; .T.
 * ...    .H.    .H.
 * ...    ...    ...
 * </code></pre>
 * <p>Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:</p>
 * <pre><code>
 * .....    .....    .....
 * .....    ..H..    ..H..
 * ..H.. -&gt; ..... -&gt; ..T..
 * .T...    .T...    .....
 * .....    .....    .....
 *
 * .....    .....    .....
 * .....    .....    .....
 * ..H.. -&gt; ...H. -&gt; ..TH.
 * .T...    .T...    .....
 * .....    .....    .....
 * </code></pre>
 * <p>You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.</p>
 * <p>For example:</p>
 * <pre><code>
 * R 4
 * U 4
 * L 3
 * D 1
 * R 4
 * D 1
 * L 5
 * R 2
 * </code></pre>
 * <p>This series of motions moves the head <em>right</em> four steps, then <em>up</em> four steps, then <em>left</em> three steps, then <em>down</em> one step, and so on.
 * After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows
 * (<code>s</code> marks the starting position as a reference point):</p>
 * <pre><code>
 * == Initial State ==
 *
 * ......
 * ......
 * ......
 * ......
 * H.....  (H covers T, s)
 *
 * == R 4 ==
 *
 * ......
 * ......
 * ......
 * ......
 * TH....  (T covers s)
 *
 * ......
 * ......
 * ......
 * ......
 * sTH...
 *
 * ......
 * ......
 * ......
 * ......
 * s.TH..
 *
 * ......
 * ......
 * ......
 * ......
 * s..TH.
 *
 * == U 4 ==
 *
 * ......
 * ......
 * ......
 * ....H.
 * s..T..
 *
 * ......
 * ......
 * ....H.
 * ....T.
 * s.....
 *
 * ......
 * ....H.
 * ....T.
 * ......
 * s.....
 *
 * ....H.
 * ....T.
 * ......
 * ......
 * s.....
 *
 * == L 3 ==
 *
 * ...H..
 * ....T.
 * ......
 * ......
 * s.....
 *
 * ..HT..
 * ......
 * ......
 * ......
 * s.....
 *
 * .HT...
 * ......
 * ......
 * ......
 * s.....
 *
 * == D 1 ==
 *
 * ..T...
 * .H....
 * ......
 * ......
 * s.....
 *
 * == R 4 ==
 *
 * ..T...
 * ..H...
 * ......
 * ......
 * s.....
 *
 * ..T...
 * ...H..
 * ......
 * ......
 * s.....
 *
 * ......
 * ...TH.
 * ......
 * ......
 * s.....
 *
 * ......
 * ....TH
 * ......
 * ......
 * s.....
 *
 * == D 1 ==
 *
 * ......
 * ....T.
 * .....H
 * ......
 * s.....
 *
 * == L 5 ==
 *
 * ......
 * ....T.
 * ....H.
 * ......
 * s.....
 *
 * ......
 * ....T.
 * ...H..
 * ......
 * s.....
 *
 * ......
 * ......
 * ..HT..
 * ......
 * s.....
 *
 * ......
 * ......
 * .HT...
 * ......
 * s.....
 *
 * ......
 * ......
 * HT....
 * ......
 * s.....
 *
 * == R 2 ==
 *
 * ......
 * ......
 * .H....  (H covers T)
 * ......
 * s.....
 *
 * ......
 * ......
 * .TH...
 * ......
 * s.....
 * </code></pre>
 * <p>After simulating the rope, you can count up all of the positions the <em>tail visited at least once</em>. In this diagram, <code>s</code> again marks the starting
 * position (which the tail also visited) and <code>#</code> marks other positions the tail visited:</p>
 * <pre><code>
 * ..##..
 * ...##.
 * .####.
 * ....#.
 * s###..
 * </code></pre>
 * <p>So, there are <code><em>13</em></code> positions the tail visited at least once.</p>
 * <p>Simulate your complete hypothetical series of motions. <em>How many positions does the tail of the rope visit at least once?</em></p>
 */
public class Main implements Runnable {
    private static final Pattern PATTERN = Pattern.compile("(\\w) (\\d+)");
    public static final int INITIAL_VALUE = Integer.MAX_VALUE / 2;

    @Override
    public void run() {
        try {
            final List<String> input = Util.readStringInput(getClass(), "input.txt");

            final Set<Long> visited = new HashSet<>();
            final List<Integer> bodyPartsX = new ArrayList<>();
            final List<Integer> bodyPartsY = new ArrayList<>();
            int headX, headY;
            // we don't want negative values because we need 32 bits on the left and on the right of the Long value
            // and when we cast to long the significant bit shifts to the start :)
            headX = headY = INITIAL_VALUE;
            for (int i = 0; i < 9; i++) {
                bodyPartsX.add(INITIAL_VALUE);
                bodyPartsY.add(INITIAL_VALUE);
            }

            for (String s : input) {
                final Matcher matcher = PATTERN.matcher(s);
                if (!matcher.find()) {
                    throw new IllegalStateException();
                }
                final char direction = matcher.group(1)
                                              .charAt(0);
                final int distanceToTravel = Integer.parseInt(matcher.group(2));
                for (int i = 0; i < distanceToTravel; i++) {
                    switch (direction) {
                        case 'R' -> headX++;
                        case 'L' -> headX--;
                        case 'U' -> headY--;
                        case 'D' -> headY++;
                        default -> throw new IllegalStateException();
                    }

                    int prevX = headX;
                    int prevY = headY;
                    for (int j = 0; j < 9; j++) {
                        int x = bodyPartsX.get(j);
                        int y = bodyPartsY.get(j);
                        final double distance = Math.sqrt((prevX - x) * (prevX - x) + (prevY - y) * (prevY - y));
//                        System.out.printf("<%.2f> ", distance);
                        if (distance >= 2d) {
                            x += (int) Math.signum(prevX - x);
                            y += (int) Math.signum(prevY - y);
                        }
                        bodyPartsX.set(j, x);
                        bodyPartsY.set(j, y);
                        prevX = x;
                        prevY = y;
                    }
//                    System.out.println();
//                    System.out.printf("[%d %d]", headX, headY);
//                    for (int j = 0; j < 9; j++) {
//                        System.out.printf("--[%d %d]", bodyPartsX.get(j), bodyPartsY.get(j));
//                    }
//                    System.out.println();

                    final long value = ((long) prevX << 32) | prevY;
                    visited.add(value);
                }
            }
            System.out.println(visited.size());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
